<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <!-- Exclude folder test agar tidak ikut di-compile oleh main project -->
  <ItemGroup>
    <Compile Remove="Tests\**" />
    <Compile Remove="MS_USER.Tests\**" />
    <Content Remove="Tests\**" />
    <Content Remove="MS_USER.Tests\**" />
    <EmbeddedResource Remove="Tests\**" />
    <EmbeddedResource Remove="MS_USER.Tests\**" />
    <None Remove="Tests\**" />
    <None Remove="MS_USER.Tests\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="14.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.11">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Scalar.AspNetCore" Version="2.16.20" />
  </ItemGroup>

</Project>
